# House Price Prediction

Importing Pandas library

In [ ]:
import pandas as pd

Importing Dataset

In [ ]:
path = r"https://drive.google.com/uc?export=download&id=1fx9qqGQqEQxpOizGodP3RTIZFsNeFw2L"

df = pd.read_csv(path)

In [ ]:
df.head()

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637   
1            4272             3              3        2016  4.753014   
2            3592             1              2        2016  3.634823   
3             966             1              2        1977  2.730667   
4            4926             2              1        1993  4.699073   

   Garage_Size  Neighborhood_Quality   House_Price  
0            0                     5  2.623829e+05  
1            1                     6  9.852609e+05  
2            0                     9  7.779774e+05  
3            1                     8  2.296989e+05  
4            0                     8  1.041741e+06

In [ ]:
X = df.drop('House_Price', axis=1)
Y = df['House_Price']

print('Shape of X is', X.shape)
print('Shape of Y is', Y.shape)

Shape of X is (1000, 7)
Shape of Y is (1000,)


# Splitting Dataset into Test, Train


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 51)

print('Shape of X_train is ', X_train.shape)
print('Shape of Y_train is', Y_train.shape)
print('Shape of X_test is', X_test.shape)
print('Shape of Y_test is', Y_test.shape)

Shape of X_train is  (800, 7)
Shape of Y_train is (800,)
Shape of X_test is (200, 7)
Shape of Y_test is (200,)


Feature Scaling dataset

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

Simple Linear Regression - Model Training

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, Y_train)




LinearRegression()

In [ ]:
lr.coef_

array([2.50828667e+05, 1.44782628e+04, 6.79233256e+03, 2.05852815e+04,
       1.93816114e+04, 4.24543487e+03, 2.30764149e+02])

In [ ]:
lr.intercept_

np.float64(621539.4179949728)

Predict House price

In [ ]:
X_test[0, :]

array([ 0.71470781, -0.69033363,  1.26368574,  0.78495102,  0.54793456,
       -0.02619073,  0.48437603])

In [ ]:
lr.predict([X_test[0, :]])

array([826176.04520092])

In [ ]:
lr.predict(X_test)

array([ 826176.04520092,  813752.28074574,  907178.30722058,
        780775.5081472 ,  556688.13133019,  656193.85342275,
        864384.66168694,  885194.39802141,  321056.11131493,
        522866.52061628,  921360.97461084,  829539.29097832,
        352428.96133331,  581636.11559569,  507818.5542191 ,
        503632.87597024,  715243.30330852,  461638.92244147,
        289914.27197341, 1106720.49275835,  248432.87847615,
        662481.09144571,  916751.95066764,  375436.80846573,
        974821.16211894,  267159.64678942,  753528.99855611,
        232348.44036216,  731993.14289034,  857812.79352503,
        770086.85154362,  209823.62655799,  895784.87637235,
       1070486.85946468,  569778.32964285,  356886.88875382,
       1099329.86572756,  250380.5199944 ,  382871.9456172 ,
        436047.94319707,  281828.89740112,  625432.6304551 ,
        377575.42622902,  620793.25830197,  894042.88895396,
        223279.80287921,  826467.41784544,  424021.63795251,
        649946.94703865,

In [ ]:
Y_test

833    816939.587431
551    809782.166226
782    891638.508696
535    788284.690202
144    551859.085695
           ...      
975    571367.825279
971    345655.794855
366    738935.819446
479    246540.965936
870    796875.092782
Name: House_Price, Length: 200, dtype: float64

In [ ]:
lr.score(X_test, Y_test)

0.9985209063066427